name: Build XNAV Configurator
on: 
  pull_request:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=xnav-configurator_linux_x64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: sudo apt-get update && sudo apt-get -y install dpkg fakeroot rpm build-essential libudev-dev
      - run: npm install --foreground-scripts
      - run: rm -v resources/sitl/linux/arm64/inav_SITL || true
      - run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_DEB
          path: ./out/make/deb/x64/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_RPM
          path: ./out/make/rpm/x64/*.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_ZIP
          path: ./out/make/zip/linux/x64/*.zip

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=xnav-configurator_linux_aarch64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: sudo apt-get update && sudo apt-get -y install dpkg fakeroot rpm build-essential libudev-dev
      - run: npm install --foreground-scripts
      - run: mv -fv resources/sitl/linux/arm64/inav_SITL resources/sitl/linux/xnav_SITL || true
      - run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_DEB
          path: ./out/make/deb/arm64/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_RPM
          path: ./out/make/rpm/arm64/*.rpm
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}_ZIP
          path: ./out/make/zip/linux/arm64/*.zip

  build-mac-arm64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAMEarm64=xnav-configurator_MacOS_arm64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: python3 -m pip install --break-system-packages setuptools
      - run: npm install --foreground-scripts
      - run: npm run make -- --arch="arm64"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEarm64}}_ZIP
          path: ./out/make/zip/darwin/arm64/*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEarm64}}_DMG
          path: ./out/make/*arm64*.dmg

  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAMEx64=xnav-configurator_MacOS_x64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: python3 -m pip install --break-system-packages setuptools
      - run: npm install --foreground-scripts
      - run: npm run make -- --arch="x64"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEx64}}_ZIP
          path: ./out/make/zip/darwin/x64/*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEx64}}_DMG
          path: ./out/make/*x64*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: choco install --force -y awk grep sed
      - name: Setup environment
        shell: bash
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAMEx64=xnav-configurator_Windows64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: engineerd/configurator@v0.0.10
        with: 
          name: "Wix Toolset 3.1.4"
          url: "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip"
          pathInArchive: "/"
      - run: npm install --foreground-scripts
      - run: npm run make -- --arch="x64"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEx64}}_ZIP
          path: ./out/make/zip/win32/x64/*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEx64}}_MSI
          path: ./out/make/wix/x64/*.msi

  build-windows-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: choco install --force -y awk grep sed
      - name: Setup environment
        shell: bash
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep version package.json | sed 's/.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/g')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAMEia32=xnav-configurator_Windows32_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: engineerd/configurator@v0.0.10
        with: 
          name: "Wix Toolset 3.1.4"
          url: "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip"
          pathInArchive: "/"
      - run: npm install --foreground-scripts
      - run: npm run make -- --arch="ia32"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEia32}}_ZIP
          path: ./out/make/zip/win32/ia32/*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_NAMEia32}}_MSI
          path: ./out/make/wix/ia32/*.msi
