name: Build Nightly Release

on: 
  push:
    branches:
      - main
      - maintenance-*

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci.yml
    
  release:
    name: Publish Nightly Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Get version
        id: version
        run: |
          VERSION=$(grep version package.json | cut -d: -f2 | cut -d\" -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: xnav-configurator-${{ env.VERSION }}-dev-${{ steps.date.outputs.today }}-${{ github.run_number }}-${{ github.sha }}
          tag_name: v${{env.VERSION}}-${{ steps.date.outputs.today }}.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: jeevesh326/xnav-configurator
          prerelease: true
          draft: false
          make_latest: false
          files: |
            artifacts/*
          body: |
            ### XNAV Configurator Nightly Build

            ✅ This is an automated nightly build of XNAV Configurator.

            ### MacOS builds
            MacOS builds are not signed, so you will need to run:
            ```bash
            xattr -cr /path/to/your/XNAV Configurator.app
            ```
            to remove warnings about downloaded applications.

            ### Repository:
            ${{ github.repository }} ([link](${{ github.event.repository.html_url }}))

            ### Branch:
            ${{ github.ref_name }} ([link](${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}))

            ### Latest changeset:
            ${{ github.event.head_commit.id }} ([link](${{ github.event.head_commit.url }}))

            ### Changes:
            ${{ github.event.head_commit.message }}
